name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    name: Setup
    runs-on: windows-latest
    steps:
      - name: Download, extract, and delete 2hu toolkit
        run: |
          Invoke-WebRequest https://github.com/thpatch/thtk/releases/download/12/thtk-bin-12.zip -OutFile thtk.zip 
          Expand-Archive thtk.zip -DestinationPath ${{ runner.temp }} && Remove-Item thtk.zip
      - name: Tests
        run: |
          Get-ChildItem -Path ${{ runner.temp}}\thtk-bin-12
          ${{ runner.temp}}\thtk-bin-12\thanm.exe
          $THDAT = '${{ runner.temp}}\thtk-bin-12\thdat.exe'
          & $THDAT  

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: Write-Host Hello, world! The files are on ${{ runner.temp }} or $THDAT

      # Runs a set of commands using the runners shell
      - name: Current directory
        run: |
          Get-ChildItem
          
      # Build artifact of th08.dat
